name: deploying vuepress project to server
on:
  push:
    branches:
      - master # main 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%dT.%H.%M.%S')"

      - name: Build static files
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ github.token }}
          TARGET_REPO: 12306hujunjie/blog
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: ./public
      # - name: Deploy to Server
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #       SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      #       ARGS: -rltgoDzvO --delete
      #       SOURCE: ./public/
      #       REMOTE_HOST: ${{ secrets.SSH_HOST }}
      #       REMOTE_USER: ${{ secrets.SSH_USRNAME }}
      #       TARGET: /root/project/blog/static
      #       EXCLUDE: 
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
    
      - name: login to aliyun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com/uther-cms/blog
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/uther-cms/blog:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prep helm chart
        run: |
          sed -i " s/^version:.*$/version: ${{ steps.date.outputs.date }} / " helm-chart/Chart.yaml
          sed -i " s/^appVersion:.*$/appVersion: ${{ steps.date.outputs.date }} / " helm-chart/Chart.yaml

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade my-blog ./helm-chart/ --install --wait --atomic --namespace=default --set=image.tag=${{ github.sha }}
          kubeconfig: "${{ secrets.KUBECONFIG }}"

      # - name: deploy
      #   uses: glopezep/helm@v1.7.1
      #   with:
      #     release: my-blog
      #     namespace: default
      #     chart: helm-chart
      #     version: ${{ github.sha }}
      #     token: ${{ github.token }}
      #     helm: helm3
      #     values: |
      #       image:
      #         tag: ${{ github.sha }}
      #   env: 
      #     KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}